Repository RenanCDev/TraininSync, pull requests merged in 2025-05, with the labels that each got.

#78 #75 feat personal register
  traininSync-front/package-lock.json
  traininSync-front/package.json
  traininSync-front/src/api/personal/createPersonal.ts
  traininSync-front/src/api/personal/getPersonal.ts
  traininSync-front/src/components/button/index.tsx
  traininSync-front/src/global.css
  traininSync-front/src/main.tsx
  traininSync-front/src/pages/login/index.tsx
  traininSync-front/src/pages/login/zod.ts
  traininSync-front/src/pages/register-personal/index.tsx
  traininSync-front/src/pages/register-personal/zod.ts
  traininSync-front/src/pages/register/index.tsx
  traininSync-front/src/pages/register/zod.ts
  traininSync-front/src/services/api.ts
  traininSync-front/src/utils/celular/format.ts
  traininSync-front/src/utils/cpf/cpf-validation.ts
  traininSync-front/src/utils/cpf/format.ts
Labels: bug, enhancement

#82 #80: adding missing models (except Pagamento)
  traininSync-back/traininsync/models.py
  traininSync-back/traininsync/serializers.py
  traininSync-back/traininsync/templates/api_home.html
  traininSync-back/traininsync/urls.py
  traininSync-back/traininsync/views.py
Labels: enhancement

#83 #81 add student screen
  traininSync-front/src/pages/register-personal/index.tsx
  traininSync-front/src/pages/register-student/index.tsx
  traininSync-front/src/routes/routes.tsx
Labels: enhancement

#84 Chore add prettier and lint
  traininSync-front/.prettierrc
  traininSync-front/README.md
  traininSync-front/commands.md
  traininSync-front/eslint.config.js
  traininSync-front/package-lock.json
  traininSync-front/package.json
  traininSync-front/src/api/personal/createPersonal.ts
  traininSync-front/src/pages/register-personal/index.tsx
  traininSync-front/src/utils/cpf/cpf-validation.ts
Labels: bug, enhancement

#85 #79/separatin serializers
  traininSync-back/traininsync/models.py
  traininSync-back/traininsync/serializers.py
  traininSync-back/traininsync/serializers/__init__.py
  traininSync-back/traininsync/serializers/agendaserializer.py
  traininSync-back/traininsync/serializers/alunoserializer.py
  traininSync-back/traininsync/serializers/contratodeservicoserializer.py
  traininSync-back/traininsync/serializers/dadosbancariosserializers.py
  traininSync-back/traininsync/serializers/personalserializer.py
  traininSync-back/traininsync/serializers/pessoaserializers.py
  traininSync-back/traininsync/serializers/registrodeprogressoserializer.py
  traininSync-back/traininsync/serializers/servicoserializer.py
Labels: enhancement

#89 #87 add pré commit to project
  traininSync-back/.pre-commit-config.yaml
  traininSync-back/.pylintrc
  traininSync-back/isort.cfg
  traininSync-front/.pre-commit-config.yaml
Labels: enhancement

#88 #86/adding pagamento
  traininSync-back/traininsync/models.py
  traininSync-back/traininsync/serializers.py
  traininSync-back/traininsync/serializers/pagamentoserializer.py
  traininSync-back/traininsync/templates/api_home.html
  traininSync-back/traininsync/urls.py
  traininSync-back/traininsync/views.py
Labels: enhancement

#92 #91/fixing .serializers folder and init file
  traininSync-back/traininsync/serializers.py
  traininSync-back/traininsync/serializers/__init__.py
Labels: bug

#98 #93/projeto02 task
  Documentos/Documento de APF.md
  Documentos/Documento de Arquitetura do Projeto.md
  Documentos/Documento de Iteração e Releases.md
  Documentos/Documento de User Stories.md
  Documentos/Documento de Visão.md
  Imagens/arquiteturaprojantiga.png
  Imagens/arquiteturaprojatualizada.png
  traininSync-back/traininsync/migrations/0003_rename_aguacorporaltotal_aluno_agua_corporal_total_and_more.py
Labels: bug, documentation

#100 #99/ Adding the String Post and Get verification at serializers
  Imagens/arquiteturaprojantiga.png
  traininSync-back/traininsync/models.py
  traininSync-back/traininsync/serializers/alunoserializer.py
  traininSync-back/traininsync/serializers/personalserializer.py
  traininSync-back/traininsync/serializers/serializers_base.py
Labels: enhancement

#107 Feat: I create tests file for each models-class presents in models,py
  traininSync-back/setup/settings.py
  traininSync-back/traininsync/.pylintrc
  traininSync-back/traininsync/tests.py
  traininSync-back/traininsync/tests/__init__.py
  traininSync-back/traininsync/tests/models_agenda_test.py
  traininSync-back/traininsync/tests/models_aluno_test.py
  traininSync-back/traininsync/tests/models_contrato_de_servico_test.py
  traininSync-back/traininsync/tests/models_dados_bancarios_test.py
  traininSync-back/traininsync/tests/models_pagamento_test.py
  traininSync-back/traininsync/tests/models_personal_test.py
  traininSync-back/traininsync/tests/models_pessoa_test.py
  traininSync-back/traininsync/tests/models_registro_de_progresso_test.py
  traininSync-back/traininsync/tests/models_servico_test.py
Labels: enhancement

#112 feat: Add sonar-project file
  sonar-project.properties
Labels: enhancement
