Repository RenanCDev/TraininSync, pull requests merged in 2025-04, with the labels that each got.

#29 docs: fixes inconsistencies in readme file
  README.md
Labels: documentation

#31 feat: add front-end in this repository
  README.md
  traininSync-back/.vscode/settings.json
  traininSync-back/manage.py
  traininSync-back/traininsync/__init__.py
  traininSync-back/traininsync/asgi.py
  traininSync-back/traininsync/settings.py
  traininSync-back/traininsync/urls.py
  traininSync-back/traininsync/wsgi.py
  traininSync-back/traininsyncapp/__init__.py
  traininSync-back/traininsyncapp/admin.py
  traininSync-back/traininsyncapp/apps.py
  traininSync-back/traininsyncapp/migrations/0001_initial.py
  traininSync-back/traininsyncapp/migrations/__init__.py
  traininSync-back/traininsyncapp/models.py
  traininSync-back/traininsyncapp/tests.py
  traininSync-back/traininsyncapp/views.py
  traininSync-front/.gitignore
  traininSync-front/README.md
  traininSync-front/eslint.config.js
  traininSync-front/index.html
  traininSync-front/package-lock.json
  traininSync-front/package.json
  traininSync-front/public/vite.svg
  traininSync-front/src/App.css
  traininSync-front/src/App.tsx
  traininSync-front/src/assets/react.svg
  traininSync-front/src/index.css
  traininSync-front/src/main.tsx
  traininSync-front/src/vite-env.d.ts
  traininSync-front/tsconfig.app.json
  traininSync-front/tsconfig.json
  traininSync-front/tsconfig.node.json
  traininSync-front/vite.config.ts
Labels: enhancement

#33 docs: necessary changes in User Stories file
  Documentos/Documento de User Stories.md
Labels: documentation

#35 feat: add crud base personal
  traininSync-back/manage.py
  traininSync-back/setup/__init__.py
  traininSync-back/setup/asgi.py
  traininSync-back/setup/settings.py
  traininSync-back/setup/urls.py
  traininSync-back/setup/views.py
  traininSync-back/setup/wsgi.py
  traininSync-back/traininsync/admin.py
  traininSync-back/traininsync/apps.py
  traininSync-back/traininsync/migrations/0001_initial.py
  traininSync-back/traininsync/migrations/0002_dadosbancarios_pessoa_delete_produto_personal.py
  traininSync-back/traininsync/migrations/__init__.py
  traininSync-back/traininsync/models.py
  traininSync-back/traininsync/serializers.py
  traininSync-back/traininsync/tests.py
  traininSync-back/traininsync/urls.py
  traininSync-back/traininsync/views.py
  traininSync-back/traininsyncapp/models.py
  traininSync-back/traininsyncapp/views.py
Labels: enhancement

#37 feat: add requirements project
  requirements.txt
Labels: enhancement

#53 Add personal register screen
  traininSync-front/package-lock.json
  traininSync-front/package.json
  traininSync-front/src/App.tsx
  traininSync-front/src/components/button/index.tsx
  traininSync-front/src/components/navbar/index.tsx
  traininSync-front/src/components/register-button/index.tsx
  traininSync-front/src/pages/notFound/index.tsx
  traininSync-front/src/pages/register/index.tsx
  traininSync-front/src/routes/routes.tsx
  traininSync-front/src/tailwind.css
Labels: enhancement

#56 #48 change sgbd of project
  traininSync-back/requirements.txt
  traininSync-back/setup/settings.py
  traininSync-back/traininsync/migrations/0001_initial.py
  traininSync-back/traininsync/migrations/__init__.py
Labels: enhancement

#59 feat: adiciona os links dos scripts
  traininSync-back/scripts/p01/projeto01-Gabrielygor-q01.sql
  traininSync-back/scripts/p01/projeto01-Gabrielygor-q02.sql
  traininSync-back/scripts/p01/projeto01-LuizMiguel4444-q01.sql
  traininSync-back/scripts/p01/projeto01-LuizMiguel4444-q02.sql
  traininSync-back/scripts/p01/projeto01-RenanCDev-q01.sql
  traininSync-back/scripts/p01/projeto01-RenanCDev-q02.sql
Labels: enhancement

#61 feat:Add views to list students with active contracts and latest prog…
  traininSync-back/scripts/p01/projeto01-raelaraujo0-q01.sql
  traininSync-back/scripts/p01/projeto01-raelaraujo0-q02.sql
Labels: enhancement

#62 feat login screen
  traininSync-front/package-lock.json
  traininSync-front/package.json
  traininSync-front/public/login-image.png
  traininSync-front/src/components/arrow-back/index.tsx
  traininSync-front/src/components/navbar/index.tsx
  traininSync-front/src/pages/login/index.tsx
  traininSync-front/src/pages/register/index.tsx
  traininSync-front/src/routes/routes.tsx
Labels: enhancement

#64 feat: add swagger project #63
  traininSync-back/setup/settings.py
  traininSync-back/setup/urls.py
Labels: documentation, enhancement

#66 Testes
  requirements.txt
  traininSync-back/requirements.txt
  traininSync-back/setup/settings.py
  traininSync-back/setup/urls.py
  traininSync-back/setup/views.py
  traininSync-back/traininsync/templates/home.html
  traininSync-back/traininsync/urls.py
Labels: enhancement

#68 feat add register screen
  traininSync-front/index.html
  traininSync-front/src/App.tsx
  traininSync-front/src/components/button/index.tsx
  traininSync-front/src/global.css
  traininSync-front/src/main.tsx
  traininSync-front/src/pages/login/index.tsx
  traininSync-front/src/pages/register-personal/index.tsx
  traininSync-front/src/pages/register/index.tsx
  traininSync-front/src/routes/routes.tsx
  traininSync-front/src/tailwind.css
Labels: enhancement

#70 feat: add model n serializer for aluno and servico, and update urls n…
  traininSync-back/traininsync/models.py
  traininSync-back/traininsync/serializers.py
  traininSync-back/traininsync/urls.py
  traininSync-back/traininsync/views.py
Labels: enhancement

#73 fix: fixed the routes
  traininSync-back/traininsync/migrations/0002_servico_aluno.py
  traininSync-back/traininsync/urls.py
  traininSync-back/traininsync/views.py
Labels: bug

#77 #76 add cors unlock to project
  traininSync-back/requirements.txt
  traininSync-back/setup/settings.py
Labels: bug, enhancement
